# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'conveyor' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for conveyor
  pod 'Firebase/Core', '~>4.3.0'
  pod 'Firebase/Messaging', '~>4.3.0'

  target 'conveyor-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'conveyorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'conveyor-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for conveyor-tvOS


end
