const AUTH_START = 'AUTH_START';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';

const CONVEYORS_LOAD_ERROR = 'CONVEYORS_LOAD_ERROR';
const CONVEYORS_LOAD_START = 'CONVEYORS_LOAD_START';
const CONVEYORS_LOAD_SUCCESS = 'CONVEYORS_LOAD_SUCCESS';

const CONVEYOR_LOAD_ERROR = 'CONVEYOR_LOAD_ERROR';
const CONVEYOR_LOAD_START = 'CONVEYOR_LOAD_START';
const CONVEYOR_LOAD_SUCCESS = 'CONVEYOR_LOAD_SUCCESS';

const SET_USERNAME = 'SET_USERNAME';
const LOGOUT_USER = 'LOGOUT_USER';
const NOTIFICATIONS_LOAD_ERROR = 'NOTIFICATIONS_LOAD_ERROR';
const NOTIFICATIONS_LOAD_START = 'NOTIFICATIONS_LOAD_START';
const NOTIFICATIONS_LOAD_SUCCESS = 'NOTIFICATIONS_LOAD_SUCCESS';

export {
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_ERROR,
  SET_USERNAME,
  LOGOUT_USER,
  CONVEYORS_LOAD_START,
  CONVEYORS_LOAD_SUCCESS,
  CONVEYORS_LOAD_ERROR,
  CONVEYOR_LOAD_START,
  CONVEYOR_LOAD_SUCCESS,
  CONVEYOR_LOAD_ERROR,
  NOTIFICATIONS_LOAD_ERROR,
  NOTIFICATIONS_LOAD_START,
  NOTIFICATIONS_LOAD_SUCCESS
};
